dubbo:
  application:
    name: boot-order-service-consumer
#  scan:
#    base-packages: org.apache.dubbo.spring.boot.sample.provider.service
  registry:
    address: consul://127.0.0.1:8500
  monitor:
    protocol: registry
server:
  port: 8081
